version: '3'
networks:
  db-data-net:
    driver: bridge
services:
  pythonapp:
    image: todoapp:3.0.0 #tyt
    build:
      context: .
      dockerfile: Dockerfile #tyt
    container_name: todoapp #tyt
    ports:
      - "8089:8080" #tyt
    environment:
      - ENV=local
    networks:
      - db-data-net
    depends_on:
      - mysql
    restart: unless-stopped
  mysql:
    image: mysql-local:2.0.0 #tyt
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: my-sql
    ports:
      - "3307:3306" #tyt
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=1234
    networks:
      - db-data-net
volumes:
  db-data: