version: '3.1'

networks:
  db-data-net:
    driver: bridge


services:

  db:
    image: fredisson11/mysql-local:1.0.0
    container_name: db-container
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: 1234
    networks:
      - db-data-net

  todo-app:
    image: todoapp:2.0.0
    build: ./
    container_name: todo-app-container
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=Development
    networks:
      - db-data-net
    depends_on:
      - db

volumes:
  db_data:
